# Generated by Django 4.1.3 on 2022-12-07 21:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('exercise_app', '0002_passworkouts_exercise'),
    ]

    operations = [
        migrations.AddField(
            model_name='passworkouts',
            name='workout_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
