# Generated by Django 4.1.3 on 2022-12-08 22:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exercise_app', '0003_passworkouts_workout_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='passworkouts',
            name='user_passWorkouts',
        ),
        migrations.DeleteModel(
            name='Exercise',
        ),
        migrations.DeleteModel(
            name='PassWorkouts',
        ),
    ]
