# Generated by Django 4.1.3 on 2022-12-08 22:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import exercise_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('exercise_app', '0004_remove_passworkouts_user_passworkouts_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PassWorkouts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exercise', models.CharField(max_length=200)),
                ('muscile_group', models.CharField(max_length=50)),
                ('reps', models.CharField(max_length=50)),
                ('weight', models.CharField(max_length=50)),
                ('workout_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('user_passWorkouts', models.ForeignKey(on_delete=models.SET(exercise_app.models.get_deleted_user_instance), related_name='exercise', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('muscile_group', models.CharField(max_length=50)),
                ('equipment', models.CharField(max_length=50)),
                ('workout_type', models.CharField(max_length=50)),
                ('week_day', models.IntegerField()),
                ('exercise_title', models.CharField(max_length=50)),
                ('reps', models.IntegerField()),
                ('weight', models.IntegerField()),
                ('user_exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='MusicleGroup', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
