# Generated by Django 4.1.3 on 2022-12-09 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercise_app', '0005_passworkouts_exercise'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercise',
            name='week_day',
        ),
        migrations.AlterField(
            model_name='exercise',
            name='reps',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='weight',
            field=models.IntegerField(default=0),
        ),
    ]
